### ISSUE TITLE
BMPopoverController missing mashup loaded event

### ISSUE THREAD

**Issue by enthusiasc** [BogdanMihaiciuc/BMPresentationController#29]
Hi,
i found that the BMPopoverController is no longer working properly on thingworx 9.2.8. There was no issue with thingworx 9.2.3.

You can import attached mashups to reproduce the behaviour. In "Test" mashup there is an arbitrary service call
 invoked on mashup loaded. When you run "Test" mashup you will see that the service is invoked. When you open the mashup with BMPopoverController (reference mashup "Main") the popup will open, but the service call is missing. I also tried to invoke an expression that would log to console on mashup loaded - which would also not show up in the console when the popup opens.

[bugreport.zip](https://github.com/BogdanMihaiciuc/BMPresentationController/files/9092505/bugreport.zip)
Thanks

**Comment by BogdanMihaiciuc** [comment]
I've managed to find out what's causing this and will try to publish an update early next week to resolve it

**Comment by BogdanMihaiciuc** [comment]
The latest release, 2.8.4, should fix this in [presentation controller](https://github.com/BogdanMihaiciuc/BMPresentationController/releases/tag/2.8.4) and [core ui widgets](https://github.com/ptc-iot-sharing/BMCoreUIWidgets/releases/tag/2.8.4).

Please reopen if you're still seeing issues.

**Comment by enthusiasc** [comment]
Thanks, the latest release 2.8.4 solves the issue.
