### ISSUE TITLE
Z-Index values for BMPopoverOverlay and BMPopover 

### ISSUE THREAD

**Issue by stefan-lacatus** [BogdanMihaiciuc/BMPresentationController#7]
We are facing the following bug at the moment:
* A mashup displayed in a BMPopoverController contains a Navigation widget
* The navigation widget opens a modal popup (or a BMWindowController)
* When the user clicks on the popup mashup, the Popover closes, also closing the popup

This seems to be because in the `BMPopoverOverlay` has a z-index set to 9999999 so it consumes the click event that should go to the popup (z-index 15001 on Thingworx 8.5.3)

The workaround we have in place right now is to set the z-index on BMPopoverOverlay to 15000, so it will sit behind the mashup and its overlay.

Also a change to the `BMPopover BMKeyWindow` div is needed, setting the z-index to 15000 (from the auto value), otherwise the popver itself will appear on top of the mashup.
However this would break popovers that should be displayed in a modal popup.

Is my workaround the correct approach? Can it be added to the official code?
If not, what should be the correct way to do it?

**Comment by BogdanMihaiciuc** [comment]
Please reopen if this is still an issue with the current version.
